# Importing

In [1]:
import numpy as np

In [2]:
## Check version

In [3]:
np

<module 'numpy' from '/home/codespace/.local/lib/python3.12/site-packages/numpy/__init__.py'>

## Creating arrays

In [4]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [7]:
a = np.array([1, 2, 3])

In [8]:
a[1]

np.int64(2)

In [9]:
a[2] = 100
a

array([  1,   2, 100])

In [10]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [12]:
np.linspace(0, 100)

array([  0.        ,   2.04081633,   4.08163265,   6.12244898,
         8.16326531,  10.20408163,  12.24489796,  14.28571429,
        16.32653061,  18.36734694,  20.40816327,  22.44897959,
        24.48979592,  26.53061224,  28.57142857,  30.6122449 ,
        32.65306122,  34.69387755,  36.73469388,  38.7755102 ,
        40.81632653,  42.85714286,  44.89795918,  46.93877551,
        48.97959184,  51.02040816,  53.06122449,  55.10204082,
        57.14285714,  59.18367347,  61.2244898 ,  63.26530612,
        65.30612245,  67.34693878,  69.3877551 ,  71.42857143,
        73.46938776,  75.51020408,  77.55102041,  79.59183673,
        81.63265306,  83.67346939,  85.71428571,  87.75510204,
        89.79591837,  91.83673469,  93.87755102,  95.91836735,
        97.95918367, 100.        ])

In [13]:
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

## Multi-dimentional arrays

In [14]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [15]:
b = np.array([[1,2], [3,4], [5,6]])
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [16]:
b[1][1]

np.int64(4)

In [17]:
b[1][1] = 100

In [18]:
b

array([[  1,   2],
       [  3, 100],
       [  5,   6]])

In [19]:
b[:, 1]

array([  2, 100,   6])

In [20]:
b[:]

array([[  1,   2],
       [  3, 100],
       [  5,   6]])

## randomly generated arrays

In [21]:
np.random.rand(5, 2) #pseudo random

array([[0.19825432, 0.13362347],
       [0.24018311, 0.21821145],
       [0.69117597, 0.51412641],
       [0.78984574, 0.59457715],
       [0.34703149, 0.28696664]])

In [22]:
np.random.seed(2)
np.random.rand(5, 2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [23]:
np.random.rand(5, 2) * 100

array([[62.11338328, 52.91420943],
       [13.45799453, 51.35781213],
       [18.44398656, 78.53351478],
       [85.39752926, 49.42368374],
       [84.65614854,  7.9645477 ]])

In [24]:
np.random.randint(low=0, high=100, size=(5, 2))

array([[68, 46],
       [70, 95],
       [83, 31],
       [66, 80],
       [52, 76]])

## Element wise operations

In [25]:
c = np.arange(5)
c

array([0, 1, 2, 3, 4])

In [26]:
c + 1

array([1, 2, 3, 4, 5])

In [27]:
c * 2

array([0, 2, 4, 6, 8])

In [28]:
(10 + (c * 2))

array([10, 12, 14, 16, 18])

## comparison operations

In [29]:
d = np.arange(5)
e = np.array([-1, -5, 2, 7, 8])

In [30]:
d > e

array([ True,  True, False, False, False])

In [31]:
d[d > e] # returns the elements that are true.

array([0, 1])

In [32]:
## Summarizing operations

In [33]:
d.min()

np.int64(0)

In [34]:
d.max()

np.int64(4)

In [35]:
d.mean()

np.float64(2.0)

In [36]:
d.std()

np.float64(1.4142135623730951)